In [1]:
import numpy as np

###### Create the array

In [3]:
x = np.array([56,12,35,48,71,11,28])

In [5]:
print(x)

[56 12 35 48 71 11 28]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [9]:
x.dtype

dtype('int64')

In [10]:
a = 356466326463526346457654743639678585848659809684659

In [11]:
a

356466326463526346457654743639678585848659809684659

In [12]:
a=458**234

In [13]:
a

43905795767991864094969008433853843727765190672755424260323651596770908692463752063349544254446208579317901745636582787109593466824101355870144112225510376448295784994526579552543018884305543044493309296858682300669941538488425682799969171583395923990520786806290244859200327120798115376585778512958867490512130433791363025204928943749007327241909748104181755555514716123701093390972916167581670320194990851096421039547741011361977637389952485047878711869438405433275738041175467479259435617835450594113776974466595004076207385764811051401646402183602801610928800855856199921561691027370889997365249680218466935987350011904

In [16]:
x = np.array([56,12,35,48,71,11,28], dtype = np.int8)

In [17]:
x

array([56, 12, 35, 48, 71, 11, 28], dtype=int8)

In [19]:
x[0] = 100

In [20]:
x

array([100,  12,  35,  48,  71,  11,  28], dtype=int8)

In [21]:
x = np.array([56,12,35,48,71,11,28], dtype = np.uint8)

In [22]:
x

array([56, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [24]:
x[0] = 145

In [25]:
x

array([145,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [26]:
x.size

7

In [27]:
x.shape

(7,)

In [28]:
x.min()

11

In [29]:
x.max()

145

In [30]:
x.mean()

50.0

In [32]:
x.sort()
x

array([ 11,  12,  28,  35,  48,  71, 145], dtype=uint8)

In [33]:
x.std()

43.33260072640789

In [35]:
x.sum()

350

In [36]:
y = np.array([67, 89, 45.34, 69, 11, 35])

In [37]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [38]:
y.dtype

dtype('float64')

In [39]:
z = np.array([67, 89, 45.34, 69, 11, True])

In [40]:
z

array([67.  , 89.  , 45.34, 69.  , 11.  ,  1.  ])

In [41]:
z = np.zeros(10)

In [42]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
z = np.zeros(10, dtype=np.int16)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [44]:
o = np.ones(10, dtype=np.int16)
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [47]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [48]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [49]:
np.arange(0, 10, 0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [50]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

###### Array Operations

In [52]:
num1 = np.array([56,12,33,14,68,99])
num2 = np.array([28,28,19,39,38,74])

In [53]:
num1 + 10

array([ 66,  22,  43,  24,  78, 109])

In [54]:
num2 / 5

array([ 5.6,  5.6,  3.8,  7.8,  7.6, 14.8])

In [55]:
num1 * 4

array([224,  48, 132,  56, 272, 396])

In [56]:
[56,12,33,14,68,99] * 3

[56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99]

In [57]:
num1 + num2

array([ 84,  40,  52,  53, 106, 173])

In [58]:
num1 - num2

array([ 28, -16,  14, -25,  30,  25])

##### Matrix

In [60]:
M = np.array([[4,6,7],[1,2,3],[8,0,2],[9,3,5]])

In [61]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [62]:
M.dtype

dtype('int64')

In [63]:
M.shape

(4, 3)

In [64]:
M.size

12

In [65]:
M.ndim

2

In [66]:
M[2][1]

0

In [67]:
M[2,1]

0

In [68]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [69]:
M[1:3, 0:2]

array([[1, 2],
       [8, 0]])

In [71]:
M1 = M.reshape(3,4)
M1

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [72]:
M.reshape(6,2)

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [74]:
M[1:3, 0:2] = np.array([[7,8],[1,1]])
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [75]:
M.reshape(2,-1)

array([[4, 6, 7, 7, 8, 3],
       [1, 1, 2, 9, 3, 5]])

In [76]:
M.reshape(-1,4)

array([[4, 6, 7, 7],
       [8, 3, 1, 1],
       [2, 9, 3, 5]])

In [77]:
M.reshape(-1)

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [78]:
M.flatten()

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [79]:
M.T

array([[4, 7, 1, 9],
       [6, 8, 1, 3],
       [7, 3, 2, 5]])

In [80]:
M.min()

1

In [82]:
M.min(axis=1)

array([4, 3, 1, 3])

In [83]:
M.min(axis=0)

array([1, 1, 2])

In [84]:
M.sum(axis=1)

array([17, 18,  4, 17])

In [85]:
M.sum(axis=0)

array([21, 18, 17])

In [86]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [87]:
y.reshape(3,2)

array([[67.  , 89.  ],
       [45.34, 69.  ],
       [11.  , 35.  ]])

In [88]:
M.argmax()

9

In [89]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [90]:
y.argmax()

1

In [91]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [92]:
M.dtype

dtype('int64')

In [93]:
M = M.astype(np.int16)

In [94]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]], dtype=int16)

In [95]:
M = M.astype(np.float16)
M

array([[4., 6., 7.],
       [7., 8., 3.],
       [1., 1., 2.],
       [9., 3., 5.]], dtype=float16)

In [96]:
x

array([ 11,  12,  28,  35,  48,  71, 145], dtype=uint8)

In [97]:
y = x

In [98]:
y

array([ 11,  12,  28,  35,  48,  71, 145], dtype=uint8)

In [99]:
y[0] = 20

In [100]:
x

array([ 20,  12,  28,  35,  48,  71, 145], dtype=uint8)

In [101]:
id(y)

124063689559376

In [102]:
id(x)

124063689559376

In [103]:
y = x.copy()
y

array([ 20,  12,  28,  35,  48,  71, 145], dtype=uint8)

In [104]:
id(x)

124063689559376

In [105]:
id(y)

124062770378384