In [5]:
import tensorflow as tf
import numpy as np

In [4]:
tf

<module 'tensorflow' from '/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py'>

In [6]:
# Create tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [8]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
# Create tensors
x = tf.constant([[1, 2, 3],[7,8,9]], dtype=np.int8)
y = tf.constant([[4, 5],[6,2]])

print("Tensor a:", x)
print("Tensor b:", y)

Tensor a: tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int8)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [13]:
# Create tensors
x = tf.constant([[[1, 2, 3],[7,8,9]],[[0, 2, 5],[7,6,8]]], dtype=np.int8)
y = tf.constant([[4, 5],[6,2]])

print("Tensor a:", x)
print("Tensor b:", y)

Tensor a: tf.Tensor(
[[[1 2 3]
  [7 8 9]]

 [[0 2 5]
  [7 6 8]]], shape=(2, 2, 3), dtype=int8)
Tensor b: tf.Tensor(
[[4 5]
 [6 2]], shape=(2, 2), dtype=int32)


In [14]:
# Add tensors
c = tf.add(a, b)
print("Addition:", c)

Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [15]:
a + b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [16]:
# Subtract tensors
d = tf.subtract(a, b)
print("Subtraction:", d)

Subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [17]:
a - b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [18]:
d.numpy()

array([-3, -3, -3], dtype=int32)

In [19]:
a.numpy()

array([1, 2, 3], dtype=int32)

In [20]:
# Multiply tensors
e = tf.multiply(a, b)
print("Multiplication:", e)

Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [21]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [22]:
# Divide tensors
f = tf.divide(a, b)
print("Division:", f)

Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [24]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [25]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [26]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2], dtype=int32)>

In [27]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [28]:
# Matrix multiplication
a_matrix = tf.constant([[1, 2], [3, 4]])
b_matrix = tf.constant([[5, 6], [7, 8]])

g = tf.matmul(a_matrix, b_matrix)
print("Matrix Multiplication:", g)

Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
